### ISSUE TITLE
Create tippy Programmatically

### ISSUE THREAD

**Issue by rmpt** [ngneat/helipopper#102]
## I'm submitting an issue

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The example have a variable conflict, both TippyService and TippyInstance have the same variable name. That's issue one.
After fixing this, when I call: 
` const myTippyInstance = this.tippyService.create(element, 'this field is required', { arrow: true });`

I can't call `myTippyInstance.open()` because:
`Property 'open' does not exist on type 'ExtendedTippyInstance<"this field is required">'.`

I've cast the result of create to `any` but still get the error on the console, but the tooltip shows correctly. What should I do to avoid this crash?

## Expected behavior

`create` function should return a type that allows to call `open` method right away. Apart of that, the crash is weird in the sense that the tooltip shows, so no error should be shown.

## Minimal reproduction of the problem with instructions

Simple angular 13 app applying the simplest example, the one on your github page.

## What is the motivation / use case for changing the behavior?

Tooltip over calendar events.

## Environment

<pre><code>
Angular version: 13.3.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 101.0.1
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by samerkh** [comment]
why is this ignored? I've always had an issue creating tippy programatically
[This part of the documentation](https://github.com/ngneat/helipopper/tree/v5.1.4#create-tippy-programmatically) is not correct, specifically the declaration of the instance and the service (they both are named tippy)
and there is no .open in tippy instance (.show exists) 
and finally when i try tippyService.create(element,'text') i get this error
`TypeError: Cannot read properties of undefined (reading 'undefined')`

**Comment by samerkh** [comment]
@rmpt were you able to solve the issue?

**Comment by shaharkazaz** [comment]
@rmpt This is only a mistake in the docs. the method should be `show`. I'll update.

@samerkh I'm not sure what's the issue you are describing, you are welcome to open an issue with a reproduction repo/stackblitz.

**Comment by samerkh** [comment]
@shaharkazaz thanks for your reply. I did not import the TippyModule in the AppModule, but rather into a sub module, the general config was not set to the data i provided inside .forRoot(). I fixed the issue by importing the TippyModule inside AppModule.
However, i believe there is still an issue in documentation, i made a PR you can look into.
Thanks!
