### ISSUE TITLE
How to check if helipopper is opened

### ISSUE THREAD

**Issue by timhecker** [ngneat/helipopper#11]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ x] Support request
[ ] Other... Please describe:
</code></pre>

## Expected behavior

Is there a way to check if the tooltip is opened or not? Maybe with a boolean prop? This is my actual code:
```html
  <app-icon-button
    [helipopper]="tpl"
    #contextMenu="helipopper"
    helipopperVariation="popper"
    (helipopperClose)="emitIfPopperIsOpened($event)"
  >
  </app-icon-button>

  <ng-template #tpl>
     MY CONTENT
    ....
    <button (click)="contextMenu.hide(); openModal('my-modal')">
     {{ t('commons.actions.doSomething') }}
    </button>
  </ng-template>
```

## What is the motivation / use case for changing the behavior?
I am using helipopper on a selectable table row component and I need to know the current status of tooltip (shown/hidden) to avoid the selection on that table row.

Thanks in advance.

## Environment

<pre><code>
Angular version: 10.1.0

Browser:
- [ x] Chrome (desktop) version 85
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.18.2  
- Platform:  mac

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
You're welcome to create a PR.
