### ISSUE TITLE
Tippy 6.0.0 Angular 14 Changelog

### ISSUE THREAD

**Issue by gebs** [ngneat/helipopper#115]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The [Changelog.md](https://github.com/ngneat/helipopper/blob/master/CHANGELOG.md) lists upgrade to Angular 14 in the Breaking Changes Section for Version 6.0.0. But the referenced PR shows an Update to Version 15 [e040211](https://github.com/ngneat/helipopper/commit/e04021193f063d5a3bd33334a579f2a130902f55). The Problem being that Version 6.0.0 does not seem to work with Angular 14. Following error during build:

```
Error: node_modules/@ngneat/helipopper/lib/tippy.directive.d.ts:69:18 - error TS2707: Generic type 'ɵɵDirectiveDeclaration' requires between 6 and 8 type arguments.

69     static ɵdir: i0.ɵɵDirectiveDeclaration<TippyDirective, "[tippy]", ["tippy"], { "appendTo": "appendTo"; "delay": "delay"; "duration": "duration"; "hideOnClick": "hideOnClick"; "interactive": "interactive"; "interactiveBorder": "interactiveBorder"; "maxWidth": "maxWidth"; "offset": "offset"; "placement": "placement"; "popperOptions": "popperOptions"; "showOnCreate": "showOnCreate"; "trigger": "trigger"; "triggerTarget": "triggerTarget"; "zIndex": "zIndex"; "lazy": "lazy"; "variation": "variation"; "isEnabled": "isEnabled"; "className": "className"; "onlyTextOverflow": "onlyTextOverflow"; "data": "data"; "useHostWidth": "useHostWidth"; "hideOnEscape": "hideOnEscape"; "detectChangesComponent": "detectChangesComponent"; "content": "tippy"; "customHost": "tippyHost"; "isVisible": "isVisible"; }, { "visible": "visible"; }, never, never, true, never>;
```

## Expected behavior

The Changelog.md should show the dependency to Angular 15 (and not Angular 14) for Version 6.0.0.

</code></pre>

**Comment by NetanelBasal** [comment]
We're using Angular 14 with Tippy 6.0.0 and it works. Try to remove your node modules or cache and try again.

**Comment by KeithGillette** [comment]
I get the same TS2707 error as reported by @gebs when attempting to install `@ngneat/helipopper@6.3.0` in our Angular 14.2.7 project, even after deleting `node_modules` and `package-lock.json` and then performing a fresh `npm install`.

Installing and configuring `ngneat/helipopper@5.1.4` works without error.

**Comment by NetanelBasal** [comment]
You're right. I'm fixing the changelog
