### ISSUE TITLE
@ngneat/overview 4.0.0 release breaks helipopper install

### ISSUE THREAD

**Issue by CallumDev** [ngneat/helipopper#123]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

As of the release of @ngneat/overview 4.0.0, installing helipopper now pulls down version 4, instead of version 3.0 due to the dependency being configured as `>=3.0.0` instead of `^3.0.0`

This manifests as a TIPPY_REF injection error due to the call signature for providing the injector changing.

## Expected behavior

Compatible 3.x version should be pulled, and TIPPY_REF error not observed.

## Minimal reproduction of the problem with instructions

Run the playground app with a new package.json and package.lock.json, using the npm install from the README. Clicking the popup from service will generate the error

## Environment

<pre><code>
Angular version: 15.1.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 109.0
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v18.2.1
- Platform:  Windows

**Comment by NetanelBasal** [comment]
@shaharkazaz
