### ISSUE TITLE
Bug: tippy.js `isLazy` is not a valid prop

### ISSUE THREAD

**Issue by SaulMoro** [ngneat/helipopper#134]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

(Only affect development)
Console Error with tpIsLazy Input
`tippy.esm.js:304 tippy.js 'isLazy' is not a valid prop. You may have spelled it incorrectly, or if it's a plugin, forgot to pass it in an array as props.plugins. All props: https://atomiks.github.io/tippyjs/v6/all-props/Plugins: https://atomiks.github.io/tippyjs/v6/plugins/👷‍ This is a development-only message. It will be removed in production.`

## Expected behavior

Remove isLazy on projection to tippy props

## Minimal reproduction of the problem with instructions

Any use of tpIsLazy inputs

## Environment

<pre><code>
Angular version: 15.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 16  
- Platform:  Mac 

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
@shaharkazaz
