### ISSUE TITLE
Missing release tag for 5.1.5

### ISSUE THREAD

**Issue by grunci** [ngneat/helipopper#135]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I'm submitting a documentation issue regarding releases.
In the package.json file of my application I have: 
<code>
"@ngneat/helipopper": "^5.1.4"
</code>
During npm install, I got 5.1.5.
<code>
"name": "@ngneat/helipopper",
  "version": "5.1.5",
  "description": "A Powerful Tooltip and Popover for Angular Applications",
</code>

But I cannot find this release tagged or mentioned anywhere. According to npmjs, this version (5.1.5) doesn't exist.
https://www.npmjs.com/package/@ngneat/helipopper?activeTab=versions
I need a tag for this release, since I need it for documentation purposes.
Thanks a lot in advance!
## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by shaharkazaz** [comment]
@grunci I'll try to recover, there is a good change I couldn't. I'll update

**Comment by NetanelBasal** [comment]
We couldn't find it and we're on v9. Closing this issue
