### ISSUE TITLE
Variations for lazy loaded modules

### ISSUE THREAD

**Issue by OrShalmayev** [ngneat/helipopper#136]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x ] Other... Please describe:
</code></pre>

## Current behavior
The tooltip variations provided in the root module are not accessible via lazy loaded modules.

## Expected behavior
The tooltip variations provided in the root module should be accessible from lazy loaded modules.

## Minimal reproduction of the problem with instructions
Create a root module in an Angular application that includes tooltip variations.
Create a lazy loaded module in the same application.
Attempt to access the tooltip variations from the lazy loaded module.
Notice that the tooltip variations are not accessible.

## What is the motivation / use case for changing the behavior?
The motivation for changing this behavior is to enable lazy loaded modules to utilize the tooltip variations provided in the root module. This would improve code organization and reusability, allowing developers to define tooltip variations once and use them throughout the application.

## Environment

<pre><code>
Angular version: 15

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 18  
- Platform:  mac

Others:

</code></pre>

**Comment by shaharkazaz** [comment]
This doesn't sound right, can you please share a Stackblitz reproduction of your case? Also, what version are you working with?

**Comment by NetanelBasal** [comment]
You should provide it in boostrapApplication
