### ISSUE TITLE
Running `tsc` after updating to ~8.0.0 produces `error TS2307: Cannot find module 'tippy.js' or its corresponding type declarations`

### ISSUE THREAD

**Issue by KeithGillette** [ngneat/helipopper#143]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Running `tsc` on a project importing from `@ngneat/helipopper@~8.0.0` produces:
```
node_modules/@ngneat/helipopper/lib/tippy.types.d.ts:1:33 - error TS2307: Cannot find module 'tippy.js' or its corresponding type declarations.

1 import { Instance, Props } from 'tippy.js';
```
## Expected behavior

`tsc` transpiles without error, as it did in 7.1.1.

## Minimal reproduction of the problem with instructions
Run `tsc` with default `skipLibCheck: false` on a project importing from  `@ngneat/helipopper@~8.0.0`.

## What is the motivation / use case for changing the behavior?

Project should transpile without error.

## Environment

<pre><code>
Angular version: 16.1.5

Browser:
N/A
 
For Tooling issues:
- Node version: v18.16.1
- Platform:  MacOS 13.4.1

Others:

</code></pre>

**Comment by shaharkazaz** [comment]
Are you installing your modules in legacy mode?

**Comment by KeithGillette** [comment]
Hi, @shaharkazaz: No, we don't use `--legacy-peer-deps` or `--force` on our project. `@ngneat/helipopper@7.1.1` transpiled without error.

It looks like we have to manually add `tippy.js` as a direct dependency of our project, as we do for Helipopper's previous peer dependency, `@ngneat/overview`, as documented in the `README.md`.

**Comment by shaharkazaz** [comment]
I'll add those 2 into the dependencies and that should resolve the issue and should be automatically installed.
