### ISSUE TITLE
Feature Request: Export CreateOptions, TippyProps and TIPPY_CONFIG

### ISSUE THREAD

**Issue by saurabhwizni** [ngneat/helipopper#27]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
CreateOptions, TippyProps and TIPPY_CONFIG are not present in public-api.ts

## Expected behavior
This should also be exported

## What is the motivation / use case for changing the behavior?
Due to some reason, If user cannot pass `TIPPY_CONFIG` in `forRoot`. If possible can this be exported as well so that it can be directly provided instead of adding it in forRoot.
Also `CreateOptions`, `TippyProps` are also not exported

**Comment by NetanelBasal** [comment]
Why do u need them?

**Comment by saurabhwizni** [comment]
@NetanelBasal In my use case I have to show tooltip and popover on same element, for that I cannot add same directive twice. So I created wrapper over tippy module, and created multiple directives according to different use cases and that I can separately import in any project providing TIPPY_CONFIG in providers. But as it is not exported, so I have to import tippyModule as well on the root, instead of just importing in wrapper module with forRoot.

**Comment by NetanelBasal** [comment]
Why not using two elements?

```html
<div tippy variation="popper">
  <div tippy variation="tooltip"></div>
</div>
```

**Comment by NetanelBasal** [comment]
Anyway, the only thing that makes sense to export is the TIPPY_CONFIG provider. The rest are internal. I exported it.
