### ISSUE TITLE
TemplateRef cannot work with embedded ng-container

### ISSUE THREAD

**Issue by Lonli-Lokli** [ngneat/helipopper#4]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

ng-container cannot be used as part of template ref

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-ivy-2ffvs5?file=src%2Fapp%2Fapp.component.html

Remove ng-container and other info will be shown

## What is the motivation / use case for changing the behavior?

That's a huge limitation :)

## Environment

<pre><code>
Angular version: 10

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version LATEST
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 14.4.0
- Platform:  MacOS

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
This is because ng-container isn't a real dom element. You can open a PR that filters it.

**Comment by Lonli-Lokli** [comment]
I've tried and seems like to work so my second comment should be disregarded, seems like some error when I was ttying to integrate this project.
https://stackblitz.com/edit/angular-ivy-n7s6gc?file=src%2Fapp%2Fapp.component.html

Speaking of ng-container - it's quite common situation to have ng-container in template. Interesting that having this ng-container in component opened by popper - everything is OK.

**Comment by NetanelBasal** [comment]
I'm not sure I understand. Does everything work? Can we close the issue?

**Comment by Lonli-Lokli** [comment]
Nope, ng-container still cannot be used with template-ref.

**Comment by NetanelBasal** [comment]
> This is because ng-container isn't a real dom element. You can open a PR that filters it.
