### ISSUE TITLE
[FEAT] How to get the instance of the component created by the service ?

### ISSUE THREAD

**Issue by GitHubish** [ngneat/helipopper#41]
I used the tippyService to create a dynamic popper with an Angular component like this: 

```
this.tippy = this.tippyService.create(this.suggestions.nativeElement, ContextMenuComponent, {
        variation: "popper",
        getReferenceClientRect: props.clientRect,
        appendTo: () => document.body,
        showOnCreate: true,
        interactive: true,
        trigger: 'manual',
        placement: 'auto',
        hideOnClick: false,
})
```

I would like to be able to interact with the instance of the ContextMenuComponent since this component queries an API based on what I type in an editor. Except that I don't see how to get the instance and for example do something like : 

```
this.tippy.component.myFunction(args);
```

```
export class ContextMenuComponent implements OnInit {

  constructor(
    @Inject(TIPPY_REF) tippy: TippyInstance
  ) { }

  ngOnInit(): void {
  }

  myFunction(args) {
    //NOTE: queries an API
  }
}
```

Would that be possible?  Thanks

**Comment by NetanelBasal** [comment]
Try to query `instance.view` -https://github.com/ngneat/helipopper/blob/master/projects/ngneat/helipopper/src/lib/tippy.service.ts#L33

**Comment by GitHubish** [comment]
Thank you for your answer. I don't see how to get this property view. It doesn't seem to be accessible in the instance or when the popper is visible (onShow method). Can you tell me more?

**Comment by NetanelBasal** [comment]
I'm not sure it's a good idea to expose it because it could create a memory leak if you still reference it from somewhere else outside the popper.

**Comment by GitHubish** [comment]
Ok thanks
