### ISSUE TITLE
Add closeOnEscape input

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/helipopper#42]
It's a common functionality to have the ability to close the popper when clicking the escape button.

**Comment by alenabonch** [comment]
Hello! Is that possible to add 'hideOnEscape' via global settings?

**Comment by NetanelBasal** [comment]
@konrad-va can you add it, please?

**Comment by konrad-va** [comment]
Hello! 
Yes, I will create this as soon as possible.
