### ISSUE TITLE
onShown event not firing with default popperVariation

### ISSUE THREAD

**Issue by Peltrettir** [ngneat/helipopper#54]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I'm using a slightly modified version of the default popperVariation

```TypeScript
myVariation: {
    ...popperVariation,
    appendTo: 'parent',
},
```
In my component I want to focus the first input field in the tippy's content as soon as it has appeared

```TypeScript
@ViewChild('tippy') tippy: TippyInstance;

ngAfterViewInit(): void {
    this.tooltip.setProps({
      onShown : instance => console.log('Hello from tippy')
    });
}
```
Console doesn't budge. This is simply solved by adding an animation

```TypeScript
@ViewChild('tippy') tippy: TippyInstance;

ngAfterViewInit(): void {
    this.tooltip.setProps({
      animation: 'scale',
      onShown : instance => console.log('Hello from tippy')
    });
}
```

## Expected behavior

In the [documentation](https://atomiks.github.io/tippyjs/v6/all-props/#onshown) it's said that the event relies on the CSS ***transitioned*** to fire and the [default popperVariation](https://github.com/ngneat/helipopper/blob/master/projects/ngneat/helipopper/src/lib/defaults.ts) sets the animation to null. 
Shouldn't onShown fire anyway?
If this is the intended beheviour, could you make it clearer in the documentation? 

Thanks for your consideration, 
have a great day

## Environment

<pre><code>
Angular version: 12.0.4

Browser:
- [x] Chrome (desktop) version 91.0.4472.114
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by NetanelBasal** [comment]
This is the default behavior of tippy.
