### ISSUE TITLE
Animations in with popover variant

### ISSUE THREAD

**Issue by baleeds** [ngneat/helipopper#62]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently the popover variant has no animation, and adding the animation name to the variant also doesn't result in changes.

## Expected behavior

I would like to be able to use animations for popovers. 

## Minimal reproduction of the problem with instructions

Add the package with the following variation:
```ts
    TippyModule.forRoot({
      defaultVariation: 'tooltip',
      variations: {
        popper: {
          ...popperVariation,
          animation: 'fade',
        },
      },
```

Use the popover variation.

## What is the motivation / use case for changing the behavior?

Animation is a critical part of popover UX to indicate to users the origin of the item coming into view.

## Environment

<pre><code>
Angular version: 11.2.11

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Did you include the animation style?

**Comment by baleeds** [comment]
@NetanelBasal That was my problem.  Thank you for the swift reply.
