### ISSUE TITLE
Use Component as content

### ISSUE THREAD

**Issue by LexxDer** [ngneat/helipopper#65]
Hi!

I cannot use component in tooltip as content properly. It's render on each hover below. Could you check it, pls!
https://stackblitz.com/edit/angular-10-1-10-grbcun

**Comment by NetanelBasal** [comment]
Can you reproduce it in our playground?

**Comment by LexxDer** [comment]
Yes, I have reproduced on local playground, but on your live it works. 
Here it is: ![image](https://user-images.githubusercontent.com/43615558/126748526-e42702ec-d6ec-48eb-a79f-c55c32e1b70a.png)
