### ISSUE TITLE
Tooltip is not refreshed (TemplateRef as content, [data] variable)

### ISSUE THREAD

**Issue by tesseris** [ngneat/helipopper#67]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[-] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I' m Using TemplateRef as content and the [data] variable to create a tooltip. It works perfectly.
The problem is that if [data] is changed, the change is not reflected in the tooltip.

## Expected behavior

If [data] is changed the tooltip should be refreshed.

**Comment by NetanelBasal** [comment]
Please reproduce in on stackblitz.
