### ISSUE TITLE
Get data in the component

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/helipopper#74]
### Discussed in https://github.com/ngneat/helipopper/discussions/73

<div type='discussions-op-text'>

<sup>Originally posted by **admin-happ** October 29, 2021</sup>
Hello. Thank you so much for this library.

Can i get passed data `< [tippy]="tippyComponent" [data]="label" >` inside tippyComponent?

I tried to find something in `@Inject(TIPPY_REF) private readonly _tippyInstance: TippyInstance` but didn't</div>

**Comment by rhutchison** [comment]
@admin-happ are you working on this?  I saw the discussion and didn't want to hijack.

I assume you'll want to modify https://github.com/ngneat/helipopper/blob/3e8ac2c91666894b3e0f9c2f023d2301c34132af/projects/ngneat/helipopper/src/lib/tippy.directive.ts#L266 to add `this.data` to `this.instance`

**Comment by davayd** [comment]
Up!
