### ISSUE TITLE
Overflow doesn't add theme to tippy

### ISSUE THREAD

**Issue by Jobu08** [ngneat/helipopper#75]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When `onlyTextOverflow` is set to `true` and text changes so it starts overflowing, displayed tippy has wrong theme and probably other properties as well.
It seems that when any input changes all properties are reset to only newly changed ones [here](https://github.com/ngneat/helipopper/blob/master/projects/ngneat/helipopper/src/lib/tippy.directive.ts#L115)

Also another issue found during creating Stackblitz example is that when only text changes and not width of element, tippy does not react to this change. I had to change tippy width via renderer to see the tippy.

## Expected behavior

Correctly styled tippy displayed after overflow.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-ivy-xflxfu?file=src%2Fapp%2Fapp.component.ts

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [X] Chrome (desktop) version 95.0.4638.54
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Do you want to create a PR?

**Comment by Jobu08** [comment]
Sure. [PR](https://github.com/ngneat/helipopper/pull/84)
