### ISSUE TITLE
(visible) bug

### ISSUE THREAD

**Issue by shestakovich** [ngneat/helipopper#76]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

at the first click on the button, a message appears in the console, but the counter is not updated

## Expected behavior

at the first click on the button, a message appears in the console and  the counter is updated

## Minimal reproduction of the problem with instructions

```
@Component({
  selector: 'app-is-visible',
  templateUrl: './playground.component.html',
  styleUrls: ['./playground.component.scss'],
})
export class PlaygroundComponent {
  comp = ExampleComponent;

  constructor() {}
  show = true;
  counter = 1;
  handleStatus($event: boolean): void {
    this.counter = this.counter + 1;
    console.log('show tooltip', $event);
  }
}
```

template:
```
<div id="custom-component">
  <h6>Counter {{counter}}</h6>

  <div class="btn-container">
    <button class="btn btn-outline-danger" [tippy]="comp" variation="popper" (visible)="handleStatus($event)">
      Open component
    </button>
  </div>
</div>
```

## Environment

<pre><code>
Angular version: 12.0.0

Browser:
- [x] Chrome (desktop) version 95
 
For Tooling issues:
- Node version: v16.11.1
- Platform:  Linux

</code></pre>

**Comment by NetanelBasal** [comment]
If the method is called, there is nothing related to this library about the counter update issue.
