### ISSUE TITLE
document is not defined in SSR apps

### ISSUE THREAD

**Issue by johnvarv** [ngneat/helipopper#77]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Using tippy on SSR apps throws this error:
```
ERROR ReferenceError: document is not defined.
```

The error comes from [here](https://github.com/ngneat/helipopper/blob/3e8ac2c91666894b3e0f9c2f023d2301c34132af/projects/ngneat/helipopper/src/lib/tippy.directive.ts#L207)

## Expected behavior

It should not throw this error.

## Minimal reproduction of the problem with instructions

just have tippy on an angular app with SSR

## Environment

<pre><code>
Angular version: 12.2.10

 
For Tooling issues:
- Node version: 14.x
- Platform:  Linux
</code></pre>

## Note
[I've mentioned the issue before](https://github.com/ngneat/helipopper/issues/13), didn't really have time for a PR but fortunately was fixed anyway from other contributor. But maybe after the restructure I think on [2.x](https://github.com/ngneat/helipopper/compare/v1.5.5...v2.0.0) the fix was removed.

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR
