### ISSUE TITLE
Can not read property 'hide' of undefined, using templateRef

### ISSUE THREAD

**Issue by mrklika** [ngneat/helipopper#9]
## Current behavior
Can not call .hide() method of the helipopper trigger element from provided template component. Actually do not know if this is a real Helipopper problem or just casual Angular behaviour or semantic problem. 

## Expected behavior

(confirm)="removePopTriggerRef.hide()" / (close)="removePopTriggerRef.hide()" actually hides the pop and not firing error ERROR TypeError: Cannot read property 'hide' of undefined.

## Minimal reproduction of the problem with instructions
`        
<button
          mat-icon-button
          color="warn"
          [helipopper]="removePopTplRef"
          helipopperVariation="popper"
          helipopperTriggerRef="manual"
          #removePopTriggerRef="helipopper"
          (click)="activeElementId = element.id; removePopTriggerRef.show();">
          <mat-icon>delete</mat-icon>
        </button>
`

`<ng-template #removePopTplRef>
  <app-remove-pop (confirm)="removePopTriggerRef.hide()" (close)="removePopTriggerRef.hide()"></app-remove-pop>
</ng-template>`

https://stackblitz.com/edit/helipopper

**Comment by NetanelBasal** [comment]
Can you reproduce it on stackblitz? It's hard to understand.

**Comment by mrklika** [comment]
Hi, minimal StackBlitz reproduction here: https://stackblitz.com/edit/helipopper

**Comment by NetanelBasal** [comment]
It should be ` @ViewChild('removePopTriggerRef', { static: false })`

**Comment by NetanelBasal** [comment]
What do u mean? The code works. When I click the Yes button, it closes the popper.

**Comment by mrklika** [comment]
https://www.loom.com/share/48ca2676730449c09b2c0849dea46aeb

**Comment by NetanelBasal** [comment]
https://recordit.co/6NlFUI0ORS/gif/notify
